### ISSUE TITLE
More than one card swipe

### ISSUE THREAD

**Issue by hartz4k** [nickypatson/TinderSwipeView#1]
Hello,

Solve it..
Thanks..

**Comment by nickypatson** [comment]
sry I didn't get this, please be elaborative

**Comment by nickypatson** [comment]
closing the same . .. thanks

**Comment by nickypatson** [comment]
calling mutiple times the swipeView.makeRightSwipeAction()/swipeView.makeLeftSwipeAction() to acheive the requirements

**Comment by nickypatson** [comment]
closing now
