### ISSUE TITLE
Cannot fail pan gesture for button's tap gesture inside custom view

### ISSUE THREAD

**Issue by alfonse-dumadapat** [nickypatson/TinderSwipeView#10]
Hi! I wanted to put a button inside the custom view, but its tap action is not triggered, I am assuming it's because of the pan gesture of the TinderCard, and since the TinderCard is inaccessible, I cannot fail the pan gesture, or even subclass the TinderCard.

Suggestions?

Great work btw!

**Comment by nickypatson** [comment]
Good to hear that!

The reason why the UIButton is not triggered as the red/green overlay is over the UIButton.So the button won't be accessible. 
Maybe in a couple of days, I will add some bit of code to work this out and keep you posted for the same. thanks

**Comment by nickypatson** [comment]
updated the pod repo and the same is available for download. let me know your thoughts
`pod 'TinderSwipeView’ , '~> 1.1.8'`
thanks

**Comment by alfonse-dumadapat** [comment]
It works perfectly!
Thanks for the quick response! 😄

**Comment by nickypatson** [comment]
Closing now
