### ISSUE TITLE
Override green/red view overlay with custom view

### ISSUE THREAD

**Issue by alfonse-dumadapat** [nickypatson/TinderSwipeView#11]
Hi!

Again, great work!

I'm just wondering if a feature such as overriding the green/red view overlay with custom view can be added.

Thanks!

**Comment by nickypatson** [comment]
maybe in the future, I think about this. thanks

**Comment by alfonse-dumadapat** [comment]
Or maybe just a way to disable it?

**Comment by nickypatson** [comment]
setting a bool flag will make this happen.
