### ISSUE TITLE
Podspec not found

### ISSUE THREAD

**Issue by maxydey** [nickypatson/TinderSwipeView#7]
I use pod file like in example accept platform is iOS, '10.0'

mcbck$ pod install
Analyzing dependencies
[!] Unable to find a specification for `TinderSwipeView`

**Comment by nickypatson** [comment]
mention platfrom in podfile like this

`platform :ios, '10.0'`

let me know the status

**Comment by nickypatson** [comment]
Closing this issue.

**Comment by nickypatson** [comment]
Try pod repo update
