### ISSUE TITLE
Pod install 

### ISSUE THREAD

**Issue by XiangXu** [nickypatson/TinderSwipeView#9]
Hi,

First of all, thanks for sharing this library!

I tried to run pod install but I got:
[!] Unable to find a specification for `TinderSwipeView`

Can you give me any suggestion?

Thank you

**Comment by nickypatson** [comment]
mention platfrom in podfile like this

platform :ios, '10.0'

let me know the status

**Comment by XiangXu** [comment]
I tried still same, here is my pod file:

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'TinderSwipeView'

  target 'TestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by nickypatson** [comment]
Try pod repo update

**Comment by XiangXu** [comment]
Working now thanks!
